Repository TeamDeli/Deli-Back, pull requests merged in 2021-08, with the labels that each got.

#2 chore: repository 세팅
  src/main/java/com/deli/server/repository/AnniversaryRepository.java
  src/main/java/com/deli/server/repository/ProductRepository.java
  src/main/java/com/deli/server/repository/UserRepository.java
  src/main/java/com/deli/server/repository/WishListRepository.java
  src/main/java/com/deli/server/repository/dummyRepository.java
Labels: feature, kiyeon

#11 Feature/product/#8
  pom.xml
  src/main/java/com/deli/server/config/QueryDslConfiguration.java
  src/main/java/com/deli/server/controller/ProductController.java
  src/main/java/com/deli/server/dto/ProductListDto.java
  src/main/java/com/deli/server/dto/ProductSearchCondition.java
  src/main/java/com/deli/server/model/Product.java
  src/main/java/com/deli/server/repository/ProductRepository.java
  src/main/java/com/deli/server/repository/ProductRepositoryCustom.java
  src/main/java/com/deli/server/repository/ProductRepositoryImpl.java
  src/main/java/com/deli/server/service/ProductService.java
Labels: feature, sorin

#13 Feature/product/#7
  src/main/java/com/deli/server/DeliBackApplication.java
  src/main/java/com/deli/server/controller/productController.java
  src/main/java/com/deli/server/model/Product.java
  src/main/java/com/deli/server/model/SimilarProduct.java
  src/main/java/com/deli/server/repository/ProductRepository.java
  src/main/java/com/deli/server/repository/SimilarProductRepository.java
Labels: feature, kyungmin

#12 Feature/friends/#6
  pom.xml
  src/main/java/com/deli/server/controller/api/addFriendsController.java
  src/main/java/com/deli/server/dto/FriendsResponseDto.java
  src/main/java/com/deli/server/model/User.java
  src/main/java/com/deli/server/model/WishList.java
  src/main/java/com/deli/server/repository/UserRepository.java
  src/main/java/com/deli/server/repository/WishListRepository.java
  src/main/java/com/deli/server/service/AddFriendsService.java
Labels: feature, jueun

#20 Feature/product/#9
  src/main/java/com/deli/server/controller/ProductController.java
  src/main/java/com/deli/server/model/Product.java
  src/main/java/com/deli/server/service/ProductService.java
Labels: bug, sorin
